import type { AmbienceParameters } from '@/audio/ambienceModel'

/**
 * Web Audio engine for the star ambience. It owns a small, fixed node graph so a
 * star change never allocates new nodes — every parameter (pitch, cutoff, pulse,
 * drift, shimmer, noise) is automated with `setTargetAtTime`, which crossfades
 * star profiles smoothly over ~1 s instead of jumping.
 *
 * Slow movement (pulse, drift, shimmer) is generated by LFO oscillators inside
 * the graph, so nothing here needs a per-frame render loop.
 */

const PARTIAL_POOL = 5
/** Per-partial gain when a partial's model gain is 1 (kept low to avoid clutter). */
const PARTIAL_GAIN = 0.22
const NOISE_GAIN = 0.12
/** Time constant for smooth parameter changes (star-profile crossfade). */
const GLIDE_SECONDS = 0.9
const MASTER_MAX = 0.6
/** Pulse LFO modulates this resting level by ±pulseDepth. */
const DRONE_RESTING_GAIN = 0.85
const NOISE_BUFFER_SECONDS = 2

export interface StarAmbience {
  readonly context: AudioContext
  get state(): AudioContextState
  update(params: AmbienceParameters): void
  setVolume(volume: number): void
  setMuted(muted: boolean): void
  suspend(): Promise<void>
  resume(): Promise<void>
  dispose(): void
}

interface Lfo {
  osc: OscillatorNode
  depth: GainNode
}

function createNoiseBuffer(context: AudioContext): AudioBuffer {
  const length = Math.floor(context.sampleRate * NOISE_BUFFER_SECONDS)
  const buffer = context.createBuffer(1, length, context.sampleRate)
  const data = buffer.getChannelData(0)
  for (let i = 0; i < length; i += 1) data[i] = Math.random() * 2 - 1
  return buffer
}

function createLfo(context: AudioContext, frequency: number): Lfo {
  const osc = context.createOscillator()
  osc.type = 'sine'
  osc.frequency.value = frequency
  const depth = context.createGain()
  depth.gain.value = 0
  osc.connect(depth)
  osc.start()
  return { osc, depth }
}

export function createStarAmbience(): StarAmbience {
  const context = new AudioContext()

  // Conservative output chain: gentle compression keeps the drone from ever
  // spiking, so extreme stars get more texture, not more loudness.
  const compressor = context.createDynamicsCompressor()
  compressor.threshold.value = -18
  compressor.knee.value = 16
  compressor.ratio.value = 3
  compressor.attack.value = 0.05
  compressor.release.value = 0.4

  const master = context.createGain()
  master.gain.value = 0

  const filter = context.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.value = 1200
  filter.Q.value = 0.9

  const droneBus = context.createGain()
  droneBus.gain.value = DRONE_RESTING_GAIN
  droneBus.connect(filter)
  filter.connect(master)
  master.connect(compressor)
  compressor.connect(context.destination)

  const oscillators: OscillatorNode[] = []
  const partialGains: GainNode[] = []
  for (let i = 0; i < PARTIAL_POOL; i += 1) {
    const osc = context.createOscillator()
    osc.type = 'sine'
    const gain = context.createGain()
    gain.gain.value = 0
    osc.connect(gain)
    gain.connect(droneBus)
    osc.start()
    oscillators.push(osc)
    partialGains.push(gain)
  }

  // Slow LFOs drive amplitude pulse, filter drift and detune shimmer.
  const pulse = createLfo(context, 0.3)
  pulse.depth.connect(droneBus.gain)

  const drift = createLfo(context, 0.1)
  drift.depth.connect(filter.frequency)

  const shimmer = createLfo(context, 0.13)
  for (const osc of oscillators) shimmer.depth.connect(osc.detune)

  const noise = context.createBufferSource()
  noise.buffer = createNoiseBuffer(context)
  noise.loop = true
  const noiseFilter = context.createBiquadFilter()
  noiseFilter.type = 'lowpass'
  noiseFilter.frequency.value = 600
  const noiseGain = context.createGain()
  noiseGain.gain.value = 0
  noise.connect(noiseFilter)
  noiseFilter.connect(noiseGain)
  noiseGain.connect(filter)
  noise.start()

  let volume = 0.35
  let muted = false

  function applyOutputGain(): void {
    const target = muted ? 0 : MASTER_MAX * volume ** 1.6
    master.gain.setTargetAtTime(target, context.currentTime, 0.3)
  }

  function update(params: AmbienceParameters): void {
    const now = context.currentTime
    const glide = GLIDE_SECONDS

    for (let i = 0; i < PARTIAL_POOL; i += 1) {
      const osc = oscillators[i]
      const gain = partialGains[i]
      if (!osc || !gain) continue
      const partial = params.partials[i]
      if (partial) {
        osc.frequency.setTargetAtTime(params.fundamental * partial.ratio, now, glide)
        gain.gain.setTargetAtTime(partial.gain * PARTIAL_GAIN, now, glide)
      } else {
        gain.gain.setTargetAtTime(0, now, glide)
      }
    }

    filter.frequency.setTargetAtTime(params.cutoff, now, glide)
    filter.Q.setTargetAtTime(params.resonance, now, glide)

    pulse.osc.frequency.setTargetAtTime(Math.max(params.pulseRate, 0.02), now, glide)
    pulse.depth.gain.setTargetAtTime(params.pulseDepth, now, glide)

    drift.osc.frequency.setTargetAtTime(Math.max(params.driftRate, 0.01), now, glide)
    drift.depth.gain.setTargetAtTime(params.driftDepth * params.cutoff * 0.35, now, glide)

    shimmer.osc.frequency.setTargetAtTime(params.driftRate * 2.3 + 0.03, now, glide)
    shimmer.depth.gain.setTargetAtTime(params.shimmer * 14, now, glide)

    noiseGain.gain.setTargetAtTime(params.noiseLevel * NOISE_GAIN, now, glide)
  }

  function setVolume(value: number): void {
    volume = Math.min(1, Math.max(0, value))
    applyOutputGain()
  }

  function setMuted(value: boolean): void {
    muted = value
    applyOutputGain()
  }

  async function suspend(): Promise<void> {
    if (context.state === 'running') await context.suspend()
  }

  async function resume(): Promise<void> {
    if (context.state === 'suspended') await context.resume()
  }

  function dispose(): void {
    try {
      for (const osc of oscillators) osc.stop()
      pulse.osc.stop()
      drift.osc.stop()
      shimmer.osc.stop()
      noise.stop()
    } catch {
      // Already stopped.
    }
    oscillators.forEach((osc) => osc.disconnect())
    partialGains.forEach((gain) => gain.disconnect())
    pulse.depth.disconnect()
    drift.depth.disconnect()
    shimmer.depth.disconnect()
    noiseGain.disconnect()
    noiseFilter.disconnect()
    droneBus.disconnect()
    filter.disconnect()
    master.disconnect()
    compressor.disconnect()
    void context.close()
  }

  return {
    context,
    get state(): AudioContextState {
      return context.state
    },
    update,
    setVolume,
    setMuted,
    suspend,
    resume,
    dispose,
  }
}
